name: 'Setup Dynatrace Monitoring'
description: 'Deploys the OneAgent to the Kubernetes Cluster running Keptn. This action assumes that kubectl is available and connected to the correct cluster'
inputs:
  DTTenant:
    description: Dynatrace Tenant
    required: true
  DTAPIToken:
    description: Dynatrace API Token
    required: true
  DTPaaSToken:
    description: Dynatrace PaaS Token
    required: true
  KeptnSelfMonitoringProject:
    description: Name of the Keptn selfmonitoring project
    required: false
    default: 'keptn'
runs:
  using: composite
  steps:
    - shell: bash
      id: deploy_dynatrace
      env:
        DT_TENANT: ${{ inputs.DTTenant }}
        DT_API_TOKEN: ${{ inputs.DTAPIToken }}
        DT_PAAS_TOKEN: ${{ inputs.DTPaaSToken }}
        KEPTN__SELF_MONITORING_PROJECT: ${{ inputs.KeptnSelfMonitoringProject }}
      run: ${{ github.action_path }}/deploy_dynatrace.sh




